name: Android Build

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:
  workflow_call:

jobs:
  build:
    name: Build Android APK
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Extract version from tag
      id: version
      run: |
        if [[ "${{ github.ref }}" =~ ^refs/tags/v(.*)$ ]]; then
          VERSION="${BASH_REMATCH[1]}"
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "Using version: $VERSION"
        else
          echo "version=1.0.0" >> $GITHUB_OUTPUT
          echo "No tag found, using default version: 1.0.0"
        fi
      shell: bash

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'

    - name: Update package.json version
      working-directory: ./packages/android
      run: |
        npm version ${{ steps.version.outputs.version }} --no-git-tag-version --allow-same-version
      shell: bash

    - name: Setup Java
      uses: actions/setup-java@v5
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Setup Android SDK
      uses: android-actions/setup-android@v3

    - name: Install dependencies
      working-directory: ./packages/android
      run: |
        echo "Installing dependencies..."
        npm install
        echo "✓ Dependencies installed (hoisted to workspace root)"

        echo "Creating symlink to workspace node_modules..."
        ln -s ../../node_modules node_modules
        echo "✓ Symlink created: packages/android/node_modules -> ../../node_modules"

    - name: Verify babel configuration
      working-directory: ./packages/android
      run: |
        if [ ! -f "babel.config.js" ]; then
          echo "Error: babel.config.js not found!"
          exit 1
        fi
        echo "✓ babel.config.js exists"
        cat babel.config.js

    - name: Create metro config
      working-directory: ./packages/android
      run: |
        cat > metro.config.js << 'EOF'
        const {getDefaultConfig, mergeConfig} = require('@react-native/metro-config');
        const path = require('path');

        const config = {
          projectRoot: __dirname,
          watchFolders: [
            __dirname,
            path.resolve(__dirname, '../..'),
          ],
          resolver: {
            nodeModulesPaths: [
              path.resolve(__dirname, 'node_modules'),
              path.resolve(__dirname, '../../node_modules'),
            ],
          },
        };

        module.exports = mergeConfig(getDefaultConfig(__dirname), config);
        EOF
        echo "✓ Metro config created"

    - name: Initialize Android project if needed
      working-directory: ./packages/android
      run: |
        if [ ! -d "android/app" ]; then
          echo "::notice::Android native project not found, initializing..."

          # Get React Native version from package.json
          RN_VERSION=$(node -p "require('./package.json').dependencies['react-native']")
          echo "Using React Native version: $RN_VERSION"

          # Initialize React Native project with specific version
          npx react-native@${RN_VERSION} init TorChatAndroid --skip-install --version ${RN_VERSION}

          # Move android directory to correct location
          mv TorChatAndroid/android .

          # Copy package.json to keep dependencies
          cp package.json android_package.json.bak

          # Clean up temporary files
          rm -rf TorChatAndroid

          # Restore package.json
          mv android_package.json.bak package.json

          echo "::notice::Android project initialized successfully"
        else
          echo "::notice::Android project already exists, proceeding with build..."
        fi

    - name: Update Android SDK versions
      working-directory: ./packages/android/android
      run: |
        echo "Updating compileSdkVersion and targetSdkVersion for compatibility..."
        # Update compileSdkVersion to 34 (latest)
        sed -i 's/compileSdkVersion = .*/compileSdkVersion = 34/' app/build.gradle
        sed -i 's/compileSdk .*/compileSdk 34/' app/build.gradle

        # Update targetSdkVersion to 34
        sed -i 's/targetSdkVersion = .*/targetSdkVersion = 34/' app/build.gradle
        sed -i 's/targetSdk .*/targetSdk 34/' app/build.gradle

        # Update minSdkVersion to 24 (required by React Native 0.73)
        sed -i 's/minSdkVersion = .*/minSdkVersion = 24/' app/build.gradle
        sed -i 's/minSdk .*/minSdk 24/' app/build.gradle

        echo "✓ SDK versions updated (compileSdk: 34, targetSdk: 34, minSdk: 24)"

    - name: Create android assets directory and bundle JS
      working-directory: ./packages/android
      run: |
        echo "Creating assets directory..."
        mkdir -p android/app/src/main/assets

        echo "Verifying entry file exists..."
        if [ ! -f "index.js" ]; then
          echo "Error: index.js not found!"
          exit 1
        fi
        echo "✓ Entry file exists"

        echo "Bundling JavaScript and assets..."
        npx react-native bundle \
          --platform android \
          --dev false \
          --entry-file index.js \
          --bundle-output android/app/src/main/assets/index.android.bundle \
          --assets-dest android/app/src/main/res \
          --verbose

        echo "Verifying bundle was created..."
        if [ ! -f "android/app/src/main/assets/index.android.bundle" ]; then
          echo "Error: Bundle file was not created!"
          exit 1
        fi

        BUNDLE_SIZE=$(wc -c < android/app/src/main/assets/index.android.bundle)
        echo "✓ JavaScript bundle created successfully (${BUNDLE_SIZE} bytes)"

    - name: Cache Gradle packages
      uses: actions/cache@v3
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    - name: Verify Gradle setup
      working-directory: ./packages/android/android
      run: |
        echo "Checking Gradle wrapper..."
        if [ ! -f "gradlew" ]; then
          echo "Error: gradlew not found!"
          exit 1
        fi
        echo "✓ Gradle wrapper exists"

        echo "Making gradlew executable..."
        chmod +x gradlew
        echo "✓ gradlew is executable"

        echo "Verifying build.gradle files..."
        if [ ! -f "build.gradle" ]; then
          echo "Error: Root build.gradle not found!"
          exit 1
        fi
        if [ ! -f "app/build.gradle" ]; then
          echo "Error: App build.gradle not found!"
          exit 1
        fi
        echo "✓ Build files verified"

    - name: Build Debug APK
      working-directory: ./packages/android/android
      run: |
        echo "Starting Debug APK build..."
        ./gradlew assembleDebug --stacktrace --info
        echo "✓ Debug APK build completed"

    - name: Build Release APK
      working-directory: ./packages/android/android
      run: |
        echo "Starting Release APK build..."
        ./gradlew assembleRelease --stacktrace --info
        echo "✓ Release APK build completed"
      env:
        SIGNING_KEY_ALIAS: ${{ secrets.SIGNING_KEY_ALIAS }}
        SIGNING_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}
        SIGNING_STORE_PASSWORD: ${{ secrets.SIGNING_STORE_PASSWORD }}

    - name: List APK outputs
      run: |
        echo "Checking for APK files..."
        find packages/android/android/app/build/outputs/apk -name "*.apk" -type f || echo "No APK files found"

    - name: Upload Debug APK
      uses: actions/upload-artifact@v4
      with:
        name: app-debug
        path: packages/android/android/app/build/outputs/apk/debug/app-debug.apk
        retention-days: 30
        if-no-files-found: warn

    - name: Upload Release APK
      uses: actions/upload-artifact@v4
      with:
        name: app-release
        path: packages/android/android/app/build/outputs/apk/release/app-release*.apk
        retention-days: 30
        if-no-files-found: error

    - name: Verify APK exists for release
      if: startsWith(github.ref, 'refs/tags/v')
      run: |
        if [ ! -f packages/android/android/app/build/outputs/apk/release/app-release-unsigned.apk ] && [ ! -f packages/android/android/app/build/outputs/apk/release/app-release.apk ]; then
          echo "Error: Release APK not found!"
          ls -la packages/android/android/app/build/outputs/apk/release/ || true
          exit 1
        fi
        echo "Release APK found successfully"

    - name: Upload APK to Release
      if: startsWith(github.ref, 'refs/tags/v')
      uses: softprops/action-gh-release@v1
      with:
        files: |
          packages/android/android/app/build/outputs/apk/release/app-release*.apk
        fail_on_unmatched_files: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
